# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.submit_cart_request import SubmitCartRequest

class TestSubmitCartRequest(unittest.TestCase):
    """SubmitCartRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitCartRequest:
        """Test SubmitCartRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitCartRequest`
        """
        model = SubmitCartRequest()
        if include_optional:
            return SubmitCartRequest(
                channel = 1,
                device_id = 'abcd1234xyz',
                device_type = 'ANDROID',
                user_id = 1001,
                token = '550e8400-e29b-41d4-a716-446655440000',
                submit_cart_request_bean = order_api_client.models.submit_cart_request_bean.SubmitCartRequestBean(
                    cash_on_delivery = True, 
                    agree_terms = True, 
                    address = order_api_client.models.user_address_bean.UserAddressBean(
                        house = '', 
                        street = '', 
                        city = '', 
                        state = '', 
                        zip = '', 
                        country = '', 
                        phone = '', 
                        email = '', ), 
                    submit = True, )
            )
        else:
            return SubmitCartRequest(
                channel = 1,
        )
        """

    def testSubmitCartRequest(self):
        """Test SubmitCartRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
