# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.api.cart_api import CartApi


class TestCartApi(unittest.TestCase):
    """CartApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CartApi()

    def tearDown(self) -> None:
        pass

    def test_add_to_cart(self) -> None:
        """Test case for add_to_cart

        """
        pass

    def test_delete_from_cart(self) -> None:
        """Test case for delete_from_cart

        """
        pass

    def test_submit_cart(self) -> None:
        """Test case for submit_cart

        """
        pass

    def test_view_cart(self) -> None:
        """Test case for view_cart

        """
        pass


if __name__ == '__main__':
    unittest.main()
