# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.update_order_status_request_bean import UpdateOrderStatusRequestBean

class TestUpdateOrderStatusRequestBean(unittest.TestCase):
    """UpdateOrderStatusRequestBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrderStatusRequestBean:
        """Test UpdateOrderStatusRequestBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrderStatusRequestBean`
        """
        model = UpdateOrderStatusRequestBean()
        if include_optional:
            return UpdateOrderStatusRequestBean(
                id = 56,
                order_id = 56,
                status_id = 56
            )
        else:
            return UpdateOrderStatusRequestBean(
                order_id = 56,
                status_id = 56,
        )
        """

    def testUpdateOrderStatusRequestBean(self):
        """Test UpdateOrderStatusRequestBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
