# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.add_to_cart_response_bean import AddToCartResponseBean

class TestAddToCartResponseBean(unittest.TestCase):
    """AddToCartResponseBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddToCartResponseBean:
        """Test AddToCartResponseBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddToCartResponseBean`
        """
        model = AddToCartResponseBean()
        if include_optional:
            return AddToCartResponseBean(
                success = True,
                current_cart_size = 56
            )
        else:
            return AddToCartResponseBean(
        )
        """

    def testAddToCartResponseBean(self):
        """Test AddToCartResponseBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
