# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.get_order_count_response import GetOrderCountResponse

class TestGetOrderCountResponse(unittest.TestCase):
    """GetOrderCountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrderCountResponse:
        """Test GetOrderCountResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrderCountResponse`
        """
        model = GetOrderCountResponse()
        if include_optional:
            return GetOrderCountResponse(
                status = order_api_client.models.status.Status(
                    code = 56, 
                    message = '', ),
                data = order_api_client.models.order_count_bean.OrderCountBean(
                    success = True, 
                    count = 56, )
            )
        else:
            return GetOrderCountResponse(
        )
        """

    def testGetOrderCountResponse(self):
        """Test GetOrderCountResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
