# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.add_to_cart_response import AddToCartResponse

class TestAddToCartResponse(unittest.TestCase):
    """AddToCartResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddToCartResponse:
        """Test AddToCartResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddToCartResponse`
        """
        model = AddToCartResponse()
        if include_optional:
            return AddToCartResponse(
                status = order_api_client.models.status.Status(
                    code = 56, 
                    message = '', ),
                add_to_cart_response_bean = order_api_client.models.add_to_cart_response_bean.AddToCartResponseBean(
                    success = True, 
                    current_cart_size = 56, )
            )
        else:
            return AddToCartResponse(
        )
        """

    def testAddToCartResponse(self):
        """Test AddToCartResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
