# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.add_to_cart_request_bean import AddToCartRequestBean

class TestAddToCartRequestBean(unittest.TestCase):
    """AddToCartRequestBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddToCartRequestBean:
        """Test AddToCartRequestBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddToCartRequestBean`
        """
        model = AddToCartRequestBean()
        if include_optional:
            return AddToCartRequestBean(
                product_id = '',
                quantity = 56,
                unit_price = 1.337
            )
        else:
            return AddToCartRequestBean(
        )
        """

    def testAddToCartRequestBean(self):
        """Test AddToCartRequestBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
