# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.submit_cart_response import SubmitCartResponse

class TestSubmitCartResponse(unittest.TestCase):
    """SubmitCartResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitCartResponse:
        """Test SubmitCartResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitCartResponse`
        """
        model = SubmitCartResponse()
        if include_optional:
            return SubmitCartResponse(
                status = order_api_client.models.status.Status(
                    code = 56, 
                    message = '', ),
                submit_cart_response_bean = order_api_client.models.submit_cart_response_bean.SubmitCartResponseBean(
                    order_id = 56, )
            )
        else:
            return SubmitCartResponse(
        )
        """

    def testSubmitCartResponse(self):
        """Test SubmitCartResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
