# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.delete_from_cart_response_bean import DeleteFromCartResponseBean

class TestDeleteFromCartResponseBean(unittest.TestCase):
    """DeleteFromCartResponseBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteFromCartResponseBean:
        """Test DeleteFromCartResponseBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteFromCartResponseBean`
        """
        model = DeleteFromCartResponseBean()
        if include_optional:
            return DeleteFromCartResponseBean(
                success = True,
                message = ''
            )
        else:
            return DeleteFromCartResponseBean(
        )
        """

    def testDeleteFromCartResponseBean(self):
        """Test DeleteFromCartResponseBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
