# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.api.order_api import OrderApi


class TestOrderApi(unittest.TestCase):
    """OrderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrderApi()

    def tearDown(self) -> None:
        pass

    def test_get_new_orders(self) -> None:
        """Test case for get_new_orders

        """
        pass

    def test_get_order_count(self) -> None:
        """Test case for get_order_count

        """
        pass

    def test_update_order_status(self) -> None:
        """Test case for update_order_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
