# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.get_new_orders_request import GetNewOrdersRequest

class TestGetNewOrdersRequest(unittest.TestCase):
    """GetNewOrdersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNewOrdersRequest:
        """Test GetNewOrdersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNewOrdersRequest`
        """
        model = GetNewOrdersRequest()
        if include_optional:
            return GetNewOrdersRequest(
                channel = 1,
                device_id = 'abcd1234xyz',
                device_type = 'ANDROID',
                user_id = 1001,
                token = '550e8400-e29b-41d4-a716-446655440000'
            )
        else:
            return GetNewOrdersRequest(
                channel = 1,
        )
        """

    def testGetNewOrdersRequest(self):
        """Test GetNewOrdersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
