# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.submit_cart_request_bean import SubmitCartRequestBean

class TestSubmitCartRequestBean(unittest.TestCase):
    """SubmitCartRequestBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitCartRequestBean:
        """Test SubmitCartRequestBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitCartRequestBean`
        """
        model = SubmitCartRequestBean()
        if include_optional:
            return SubmitCartRequestBean(
                cash_on_delivery = True,
                agree_terms = True,
                address = order_api_client.models.user_address_bean.UserAddressBean(
                    house = '', 
                    street = '', 
                    city = '', 
                    state = '', 
                    zip = '', 
                    country = '', 
                    phone = '', 
                    email = '', ),
                submit = True
            )
        else:
            return SubmitCartRequestBean(
        )
        """

    def testSubmitCartRequestBean(self):
        """Test SubmitCartRequestBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
