# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_api_client.models.update_order_status_response_bean import UpdateOrderStatusResponseBean

class TestUpdateOrderStatusResponseBean(unittest.TestCase):
    """UpdateOrderStatusResponseBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrderStatusResponseBean:
        """Test UpdateOrderStatusResponseBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrderStatusResponseBean`
        """
        model = UpdateOrderStatusResponseBean()
        if include_optional:
            return UpdateOrderStatusResponseBean(
                success = True,
                message = ''
            )
        else:
            return UpdateOrderStatusResponseBean(
        )
        """

    def testUpdateOrderStatusResponseBean(self):
        """Test UpdateOrderStatusResponseBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
