# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.get_products_request import GetProductsRequest

class TestGetProductsRequest(unittest.TestCase):
    """GetProductsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProductsRequest:
        """Test GetProductsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProductsRequest`
        """
        model = GetProductsRequest()
        if include_optional:
            return GetProductsRequest(
                channel = 1,
                device_id = 'abcd1234xyz',
                device_type = 'ANDROID',
                user_id = 1001,
                token = 'lkj3234-2342j3n2-32kj4k23-23423',
                products_request_bean = product_api_client.models.get_products_request_bean.GetProductsRequestBean(
                    id = 56, 
                    product_ids = [
                        ''
                        ], 
                    category_id = 56, 
                    brand_id = 56, 
                    min_price = 1.337, 
                    max_price = 1.337, 
                    min_rating = 56, )
            )
        else:
            return GetProductsRequest(
                channel = 1,
        )
        """

    def testGetProductsRequest(self):
        """Test GetProductsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
