# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.get_category_drop_down_response import GetCategoryDropDownResponse

class TestGetCategoryDropDownResponse(unittest.TestCase):
    """GetCategoryDropDownResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCategoryDropDownResponse:
        """Test GetCategoryDropDownResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCategoryDropDownResponse`
        """
        model = GetCategoryDropDownResponse()
        if include_optional:
            return GetCategoryDropDownResponse(
                status = product_api_client.models.status.Status(
                    code = 56, 
                    message = '', ),
                data = product_api_client.models.category_drop_down_bean.CategoryDropDownBean(
                    success = True, 
                    categories = [
                        product_api_client.models.category_bean.CategoryBean(
                            id = 56, 
                            name = '', )
                        ], )
            )
        else:
            return GetCategoryDropDownResponse(
        )
        """

    def testGetCategoryDropDownResponse(self):
        """Test GetCategoryDropDownResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
