# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.api.product_api import ProductApi


class TestProductApi(unittest.TestCase):
    """ProductApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductApi()

    def tearDown(self) -> None:
        pass

    def test_create_product(self) -> None:
        """Test case for create_product

        """
        pass

    def test_get_product_count(self) -> None:
        """Test case for get_product_count

        """
        pass

    def test_get_products(self) -> None:
        """Test case for get_products

        """
        pass


if __name__ == '__main__':
    unittest.main()
