# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.get_products_request_bean import GetProductsRequestBean

class TestGetProductsRequestBean(unittest.TestCase):
    """GetProductsRequestBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProductsRequestBean:
        """Test GetProductsRequestBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProductsRequestBean`
        """
        model = GetProductsRequestBean()
        if include_optional:
            return GetProductsRequestBean(
                id = 56,
                product_ids = [
                    ''
                    ],
                category_id = 56,
                brand_id = 56,
                min_price = 1.337,
                max_price = 1.337,
                min_rating = 56
            )
        else:
            return GetProductsRequestBean(
        )
        """

    def testGetProductsRequestBean(self):
        """Test GetProductsRequestBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
