# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.get_product_count_request import GetProductCountRequest

class TestGetProductCountRequest(unittest.TestCase):
    """GetProductCountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProductCountRequest:
        """Test GetProductCountRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProductCountRequest`
        """
        model = GetProductCountRequest()
        if include_optional:
            return GetProductCountRequest(
                channel = 1,
                device_id = 'abcd1234xyz',
                device_type = 'ANDROID',
                user_id = 1001,
                token = 'lkj3234-2342j3n2-32kj4k23-23423'
            )
        else:
            return GetProductCountRequest(
                channel = 1,
        )
        """

    def testGetProductCountRequest(self):
        """Test GetProductCountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
