# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.get_brand_drop_down_response import GetBrandDropDownResponse

class TestGetBrandDropDownResponse(unittest.TestCase):
    """GetBrandDropDownResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBrandDropDownResponse:
        """Test GetBrandDropDownResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBrandDropDownResponse`
        """
        model = GetBrandDropDownResponse()
        if include_optional:
            return GetBrandDropDownResponse(
                status = product_api_client.models.status.Status(
                    code = 56, 
                    message = '', ),
                data = product_api_client.models.brand_drop_down_bean.BrandDropDownBean(
                    success = True, 
                    brands = [
                        product_api_client.models.category_bean.CategoryBean(
                            id = 56, 
                            name = '', )
                        ], )
            )
        else:
            return GetBrandDropDownResponse(
        )
        """

    def testGetBrandDropDownResponse(self):
        """Test GetBrandDropDownResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
