# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.brand_drop_down_bean import BrandDropDownBean

class TestBrandDropDownBean(unittest.TestCase):
    """BrandDropDownBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandDropDownBean:
        """Test BrandDropDownBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandDropDownBean`
        """
        model = BrandDropDownBean()
        if include_optional:
            return BrandDropDownBean(
                success = True,
                brands = [
                    product_api_client.models.category_bean.CategoryBean(
                        id = 56, 
                        name = '', )
                    ]
            )
        else:
            return BrandDropDownBean(
        )
        """

    def testBrandDropDownBean(self):
        """Test BrandDropDownBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
