# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.product_bean import ProductBean

class TestProductBean(unittest.TestCase):
    """ProductBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductBean:
        """Test ProductBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductBean`
        """
        model = ProductBean()
        if include_optional:
            return ProductBean(
                id = '',
                name = '',
                description = '',
                image_path = '',
                price = 1.337,
                stock = 56,
                category = '',
                brand = '',
                rating = 56
            )
        else:
            return ProductBean(
        )
        """

    def testProductBean(self):
        """Test ProductBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
