# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.get_product_count_response import GetProductCountResponse

class TestGetProductCountResponse(unittest.TestCase):
    """GetProductCountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProductCountResponse:
        """Test GetProductCountResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProductCountResponse`
        """
        model = GetProductCountResponse()
        if include_optional:
            return GetProductCountResponse(
                status = product_api_client.models.status.Status(
                    code = 56, 
                    message = '', ),
                data = product_api_client.models.product_count_bean.ProductCountBean(
                    success = True, 
                    count = 56, )
            )
        else:
            return GetProductCountResponse(
        )
        """

    def testGetProductCountResponse(self):
        """Test GetProductCountResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
