# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.api.brand_api import BrandApi


class TestBrandApi(unittest.TestCase):
    """BrandApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BrandApi()

    def tearDown(self) -> None:
        pass

    def test_get_brand_drop_down(self) -> None:
        """Test case for get_brand_drop_down

        """
        pass


if __name__ == '__main__':
    unittest.main()
