# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product_api_client.models.get_products_response_bean import GetProductsResponseBean

class TestGetProductsResponseBean(unittest.TestCase):
    """GetProductsResponseBean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProductsResponseBean:
        """Test GetProductsResponseBean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProductsResponseBean`
        """
        model = GetProductsResponseBean()
        if include_optional:
            return GetProductsResponseBean(
                success = True,
                products = [
                    product_api_client.models.product_bean.ProductBean(
                        id = '', 
                        name = '', 
                        description = '', 
                        image_path = '', 
                        price = 1.337, 
                        stock = 56, 
                        category = '', 
                        brand = '', 
                        rating = 56, )
                    ]
            )
        else:
            return GetProductsResponseBean(
        )
        """

    def testGetProductsResponseBean(self):
        """Test GetProductsResponseBean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
