# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from order_service.models.cart_item_bean import CartItemBean
from typing import Optional, Set
from typing_extensions import Self

class ViewCartBean(BaseModel):
    """
    ViewCartBean
    """ # noqa: E501
    cart_id: Optional[StrictInt] = Field(default=None, alias="cartId")
    cart_items: Optional[List[CartItemBean]] = Field(default=None, alias="cartItems")
    total_bill: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalBill")
    note: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["cartId", "cartItems", "totalBill", "note"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ViewCartBean from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in cart_items (list)
        _items = []
        if self.cart_items:
            for _item_cart_items in self.cart_items:
                if _item_cart_items:
                    _items.append(_item_cart_items.to_dict())
            _dict['cartItems'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ViewCartBean from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cartId": obj.get("cartId"),
            "cartItems": [CartItemBean.from_dict(_item) for _item in obj["cartItems"]] if obj.get("cartItems") is not None else None,
            "totalBill": obj.get("totalBill"),
            "note": obj.get("note")
        })
        return _obj


